import java.util.ArrayList;
/**
 * @author      Eli H.  && Colin V.
 * @version     1.29
 * @since       12/8/2028
 */
public class CargoPlane extends Vehicle {
    final double gasRate = 2.33;

    /**
     * Default Constructor
     */
    //============================================================================
    public CargoPlane() {

    }
    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public CargoPlane(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /**
     * Overides its superclass method. Instead, after each iteration, the range will
     * increase by 10.
     *
     * @param warehousePackages List of packages to add from
     */
    @Override
    public void fill(ArrayList<Package> warehousePackages) {


        ArrayList<Integer> x = new ArrayList<>();

        for (Package pack : warehousePackages) {
            int packZip = pack.getDestination().getZipCode();
            int zip = Math.abs(getZipDest() - packZip);
            x.add(zip);
        }


        ArrayList<Package> sending = new ArrayList<>();
        int index = 10;

        for (int i = 0; i < warehousePackages.size(); i++) {


            for (int y = 0; y < x.size(); y++) {
                if (x.get(y) <= index) {
                    if (warehousePackages.get(y).getWeight() + getCurrentWeight() <= getMaxWeight()) {
                        addPackage(warehousePackages.get(y));
                        sending.add(warehousePackages.get(y));
                    }
                }
            }


            int tempIndex = index;
            boolean stupid = true;
            for (int y = 0; y < x.size(); y++) {
                if (x.get(y) > index && stupid == true) {
                    stupid = false;
                    tempIndex = x.get(y);
                } else if (x.get(y) > index) {
                    if (x.get(y) < tempIndex) {
                        tempIndex = x.get(y);
                    }
                }
            }
            int tens = (tempIndex / 10) * 10;

            index = tens;

            if (isFull()) {
                break;
            }
            if (getPackages().size() == warehousePackages.size()) {
                break;
            }


            System.out.print("hi");
        }


    }

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Cargo Plane.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 2.33)
     * </p>
     */
    @Override
    public double getProfit() {
        /*double y = 0;
        int distance = 1;

        ArrayList<Integer> x = new ArrayList<>();

        for (Package pack : getPackages()) {
            int packZip = pack.getDestination().getZipCode();
            int zip = Math.abs(getZipDest() - packZip);
            x.add(zip);
        }

        for (int lul = 0; lul < x.size(); lul++) {
            y += getPackages().get(lul).getPrice();
            int zip = x.get(lul);
            if (distance < Math.abs(zip)) {
                distance = Math.abs(zip);

                int tens = (distance / 10);
                if (distance % 10 == 0) {

                } else {
                    tens += 10;
                }
                distance = tens;
            }
        }
        */
        double x = 0;
        int  distance = 0;

        for (Package pack : getPackages()) {
            x += pack.getPrice();
            int zip = getZipDest() - pack.getDestination().getZipCode();
            if (distance < Math.abs(zip)) {
                distance = Math.abs(zip);
            }
        }

        return x - (gasRate * distance);

    }

    /**
     * Generates a String of the Cargo Plane report. Cargo plane report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in cargo plane</li>
     * </ul>
     *
     * @return Cargo Plane Report
     */
    @Override
    public String report() {
        String x = "==============Cargo Plane Report==========" +
                "\nLicense Plate No.: " + getLicensePlate() +
                "\nDestination: " + getZipDest() +
                "\nWeight Load: " + getCurrentWeight() + "/" +
                getMaxWeight() + "\nNet Profit: " + getProfit()
                + "\n==============================\n";
        String l  = "";
        for (Package pack: getPackages()) {
            l += pack.shippingLabel();
        }

        return x + l;

    }



}

//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//1
//
//Enter Package ID:
//17FGPO8MK4
//Enter Product Name:
//Echo Dot
//Enter Weight:
//5.7
//Enter Price:
//49.99
//Enter Buyer Name:
//Lawson Computer Science Building
//Enter Address:
//304 N University St
//Enter City:
//West Lafayette
//Enter State:
//IN
//Enter ZIP Code:
//47906
//
//====================
//TO: Lawson Computer Science Building
//304 N University St
//West Lafayette, IN, 47906
//Weight:         5.70
//Price:        $49.99
//Product:Echo Dot
//====================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//2
//
//Vehicle Options:
//1) Truck
//2) Drone
//3) Cargo Plane
//1
//Enter License Plate No.:
//123ABC
//Enter Maximum Carry Weight:
//40
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//3
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Deactivate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//3
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//4
//
//Options:
//1) Send Truck
//2) Send Drone
//3) Send Cargo Plane
//4) Send First Available
//1
//ZIP Code Options:
//1) Send to first ZIP Code
//2) Send to mode of ZIP Codes
//1
//17FGPO8MK4 has been added.
//==========Truck Report==========
//License Plate No.: 123ABC
//Destination: 47906
//Weight Load: 5.70/40.00
//Net Profit: $49.99
//=====Shipping Labels=====
//====================
//TO: Lawson Computer Science Building
//304 N University St
//West Lafayette, IN, 47906
//Weight:         5.70
//Price:        $49.99
//Product:Echo Dot
//====================
//==============================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//4
//
//Error: No vehicles available.
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//5
//
//==========Statistics==========
//Profits:                    $49.99
//Packages Shipped:                1
//Packages in Warehouse:           0
//==============================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//6