import sun.awt.geom.AreaOp;

import java.util.ArrayList;


/**
 * <h1>CargoPlane</h1> Represents a Cargo Plane
 */
public class CargoPlane extends Vehicle {
    final double GAS_RATE = 2.33;

    /**
     * Default Constructor
     */
    //============================================================================
    public CargoPlane() {

    }
    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public CargoPlane(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }
    
    //============================================================================

    /**
     * Overides its superclass method. Instead, after each iteration, the range will
     * increase by 10.
     *
     * @param warehousePackages List of packages to add from
     */
    @Override
    public void fill(ArrayList<Package> warehousePackages) {

        int range = getZipDest();
        int range2 = getZipDest();
        double current = getCurrentWeight();

        for (Package pack : warehousePackages) {
            if (pack.getDestination().getZipCode() == range) {
                if(pack.getWeight() + current <= getMaxWeight()){
                    addPackage(pack);
                    warehousePackages.remove(pack);
                    current += pack.getWeight();
                }
            }
        }
        range -= 10;
        range2 += 10;

        while (isFull() == false) {
            for (Package pack : warehousePackages) {
                if (pack.getDestination().getZipCode() == range) {
                    if (pack.getWeight() + current <= getMaxWeight()) {
                        addPackage(pack);
                        warehousePackages.remove(pack);
                        current += pack.getWeight();
                    }
                }
            }
            for (Package pack : warehousePackages) {
                if (pack.getDestination().getZipCode() == range2) {
                    if (pack.getWeight() + current <= getMaxWeight()) {
                        addPackage(pack);
                        warehousePackages.remove(pack);
                        current += pack.getWeight();
                    }
                }
            }
            range -= 10;
            range2 += 10;
        }
        
    }

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Cargo Plane.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 2.33)
     * </p>
     */
    @Override
    public double getProfit() {
        int x = 0;
        int distance = getZipDest();

        for(Package pack : getPackages()) {
            x += pack.getPrice();
            int zip = getZipDest() - pack.getDestination().getZipCode();
            if(distance < Math.abs(zip)){
                distance = Math.abs(zip);
            }
        }

        return x - (GAS_RATE * distance);

    }

    /**
     * Generates a String of the Cargo Plane report. Cargo plane report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in cargo plane</li>
     * </ul>
     *
     * @return Cargo Plane Report
     */
    @Override
    public String report() {
        String x = "==============Cargo Plane Report==========" +
                "\nLicense Plate No.: " + getLicensePlate() +
                "\nDestination: " + getZipDest() +
                "\nWeight Load: " + getCurrentWeight() + "/" +
                getMaxWeight() + "\nNet Profit: " + getProfit()
                + "\n==============================\n";
        String l  = "";
        for(Package pack: getPackages()){
            l += pack.shippingLabel();
        }

        return x + l;

    }

   
   
}

//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//1
//
//Enter Package ID:
//17FGPO8MK4
//Enter Product Name:
//Echo Dot
//Enter Weight:
//5.7
//Enter Price:
//49.99
//Enter Buyer Name:
//Lawson Computer Science Building
//Enter Address:
//304 N University St
//Enter City:
//West Lafayette
//Enter State:
//IN
//Enter ZIP Code:
//47906
//
//====================
//TO: Lawson Computer Science Building
//304 N University St
//West Lafayette, IN, 47906
//Weight:         5.70
//Price:        $49.99
//Product:Echo Dot
//====================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//2
//
//Vehicle Options:
//1) Truck
//2) Drone
//3) Cargo Plane
//1
//Enter License Plate No.:
//123ABC
//Enter Maximum Carry Weight:
//40
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//3
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Deactivate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//3
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//4
//
//Options:
//1) Send Truck
//2) Send Drone
//3) Send Cargo Plane
//4) Send First Available
//1
//ZIP Code Options:
//1) Send to first ZIP Code
//2) Send to mode of ZIP Codes
//1
//17FGPO8MK4 has been added.
//==========Truck Report==========
//License Plate No.: 123ABC
//Destination: 47906
//Weight Load: 5.70/40.00
//Net Profit: $49.99
//=====Shipping Labels=====
//====================
//TO: Lawson Computer Science Building
//304 N University St
//West Lafayette, IN, 47906
//Weight:         5.70
//Price:        $49.99
//Product:Echo Dot
//====================
//==============================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//4
//
//Error: No vehicles available.
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//5
//
//==========Statistics==========
//Profits:                    $49.99
//Packages Shipped:                1
//Packages in Warehouse:           0
//==============================
//
//==========Options==========
//1) Add Package
//2) Add Vehicle
//3) Activate Prime Day
//4) Send Vehicle
//5) Print Statistics
//6) Exit
//===========================
//6